### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by fulopattila122** [bit3/git-php#13]
Hi,

first of all, thanks for this great library 👌

I'm about to use this library in one of our projects and would like to understand the status of your project.
I see the last release was more than 2 years ago. It's still working but is being tested against outdated PHP versions 5.6 - 7.2.
PHP 7.3, 7.4 and the upcoming 8.0 versions are not in the travis matrix.

I'm thinking about either submitting PRs to your repo or forking it.

- What are your plans with this project?
- What kind of PRs would you accept?
- Would you be ok dropping old PHP versions (5.6-7.2) and focus only on current ones (7.3 - 8.0)?

Thank you

**Comment by tristanlins** [comment]
@discordier are you still maintaining this library?

**Comment by discordier** [comment]
Yes, we are still actively using the library and therefore "maintaining" it.
However, we are short on man power and therefore would love PRs regarding new features.

We (@baumannsven and I) already had some discussions to rewrite the generic approach of the builders but did not come up with final decisions yet.

So:
- No, the package is not abandoned - we are still actively using it.
- The plans are to:
  - modernize it
  - add missing options to existing commands and add missing commands
  - maybe add some kind of feature detection (not all git sub commands are available everywhere)
  - add some high level constructs (like walking commits and extracting diffs from them etc.)
- We would like to see all kind of PRs from bugfixes to features
- Yes, dropping legacy PHP versions is acceptable in the next minor, however, given the current market share, we should keep 7.2 for the moment (as much as I'd love to scrape everything < 7.4, it is not feasible yet).
