### ISSUE TITLE
RevParse and --abbrev-ref switch

### ISSUE THREAD

**Issue by ghost** [bit3/git-php#6]
Hi,

I believe you have a typo at RevParseCommandBuilder.php file at line 221 (abbrevRef method).
`$this->processBuilder->add('--abbref-ref' . ($abbrev ? '=' . $abbrev : ''));`

Should be:

`$this->processBuilder->add('--abbrev-ref' . ($abbrev ? '=' . $abbrev : ''));`

Cheers

**Comment by ghost** [comment]
Here is the pull request for the issue https://github.com/bit3/git-php/pull/7

**Comment by discordier** [comment]
Closing in favor of the PR.
